name: Generate changelog
on:
  release:
    types: [created, edited]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@master
      with:
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        PATH: 'CHANGELOG.md'
        COMMIT_MESSAGE: 'docs(changelog): update release notes'
        TYPE: 'feat:Features,fix:Bug Fixes,chore:House Keeping,docs:Documentation,style:Styling,refactor:Refactor,perf:Performance Improvements,test:Tests'